#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset
# set -o xtrace

declare -r URL="$1"
declare -r EMAIL="$2"

main() {
  email_when_live
}

email_when_live() {
  ping_until_live
  mail -s "UP: ${URL}" "${EMAIL}" <<<"'${URL}' is up"
}

ping_until_live() {

  msg1 "ping -c 1 '${URL}'"

  if ping -c 1 "${URL}"; then
    return 0
  fi

  sleep 1
  ping_until_live
}

msg1() {
  local -r msg="$1"
  echo "[$(timestamp)]: ${msg}"
}

timestamp() {
  date +'%Y-%m-%d %H:%M:%S'
  # date +'%Y-%m-%dT%H:%M:%S%z'
  # date -u +'%Y-%m-%dT%H:%M:%SZ'
}

main
