#!/bin/bash

declare -r PGL="${1}";
declare -a ALL_DEVICES;
declare DEVICE;
declare PERM;
declare CURR;


_main() {
    sudo -v;
    _choose;
    _findPerm;
    _findCurr;
    _changeMac;
};

_choose() {
    ALL_DEVICES="$(
        ip link show |
        grep "^[0-9]" |
        sed -re 's/([0-9].*?):.*/\1/'
    )";

    _c green;
    local d;
    for d in "${ALL_DEVICES[@]}"; do
        echo "${d}";
    done;
    printf "\n==> Enter device: \n";
    _line;
    printf "==> ";
    _u;

    local -i choice;
    read -p "" choice;

    DEVICE="$(
        ip link show |
        grep "^${choice}" |
        sed -re 's/...(.*?):.*/\1/'
    )";
    echo "${DEVICE}";
};

_findPerm() {
    PERM="$(sudo macchanger -s "${DEVICE}"| tail -n 1)";
    PERM="${PERM#Permanent MAC: }";
};

_findCurr() {
    CURR="$(sudo macchanger -s "${DEVICE}"| head -n 1)";
    CURR="${CURR#Current MAC:   }";
};

_changeMac() {

    # nmcli d disconnect "${DEVICE}";
    # sudo ip link set "${DEVICE}" down;
    nmcli radio wifi off;

    if [[ "${CURR}" == "${PERM}" ]]; then
        sudo macchanger -a "${DEVICE}";
        [ "${PGL}" ] && pglgui &>/dev/null &disown;
    else
        sudo macchanger -p "${DEVICE}";
    fi;

    sleep 1s;

    # sudo ip link set "${DEVICE}" up;
    # nmcli d connect "${DEVICE}";
    nmcli radio wifi on;
};

_c() {

    local -r name="${1}";
    local -Ar codes=(
        ["black"]="0"
        ["red"]="1"
        ["green"]="2"
        ["yellow"]="3"
        ["blue"]="4"
        ["magenta"]="5"
        ["cyan"]="6"
        ["white"]="7"
    );
    local -r code="${codes[$name]}"

    [ -n "${code}" ] && tput setaf "${code}";

    [ -z "${*:2}" ] && return 0;

    eval "${@:2}";
    _ifErr "Failed to run '${*:2}'";

    tput sgr0;
};

_u() {
    tput sgr0;
};

_line() {
    printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' =;
};

_main;
